### ISSUE TITLE
运行出现错误 IndexError: tuple index out of range

### ISSUE THREAD

**Issue by dwm97317** [inzh/CropAndCombine-IdCard#1]
Traceback (most recent call last):
  File "E:/CropAndCombine-IdCard-master/main.py", line 207, in <module>
    getPrintImgMode1(rootPath)
  File "E:/CropAndCombine-IdCard-master/main.py", line 27, in getPrintImgMode1
    print('正在拼合身份证图像.....进度：当前处理{}，剩余{}，总共{}'.format(count, int((imgListLen/2)-count)),int((imgListLen/2)))

**Comment by big-dollar** [comment]
他这个括号写错位了
format(count, int((imgListLen/2)-count),int((imgListLen/2))))
